on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add Server to Known Hosts
      run: ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /var/www/btss-website

          echo "Pulling latest code..."
          git pull

          echo "Installing dependencies..."
          npm install --production

          echo "Building /dist directory"
          npm run build

          echo "Restarting application via PM2..."
          pm2 restart btss || pm2 start npm -- start

          pm2 save
        EOF
